### ISSUE TITLE
Reorganize to create separate chapters on How to Contribute / Guidance

### ISSUE THREAD

**Issue by MichaelRimler** [phuse-org/OSTCDA#35]
Each chapter has 'How to Contribute' and 'Guidance' subsections. This issue is to remove them and place a single (or two) non-numbered chapters at the end to provide the information in one place. And to increase readability of the core chapters.

**Comment by jonthegeek** [comment]
Should they be chapters, or contained within standard CONTRIBUTING.md and CODE_OF_CONDUCT.md in `.github` in the github repo?
